[features]
seeds = false
skip-lint = false
[programs.localnet]
stonksdefi = "EXvuR1R53eaHNaf6QL1c3yGPjAP8fyFpxU8zamMNASgG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/karan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
